services:
  mysql-monolith:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: archkit_monolith
      MYSQL_USER: archkit_user
      MYSQL_PASSWORD: archkit_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_monolith_data:/var/lib/mysql

  mysql-product:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: archkit_product
      MYSQL_USER: archkit_user
      MYSQL_PASSWORD: archkit_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_product_data:/var/lib/mysql

  mysql-inventory:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: archkit_inventory
      MYSQL_USER: archkit_user
      MYSQL_PASSWORD: archkit_password
    ports:
      - '3308:3306'
    volumes:
      - mysql_inventory_data:/var/lib/mysql

  mysql-sales:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: archkit_sales
      MYSQL_USER: archkit_user
      MYSQL_PASSWORD: archkit_password
    ports:
      - '3309:3306'
    volumes:
      - mysql_sales_data:/var/lib/mysql

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    restart: always
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --check=false
    ports:
      - '9092:9092'
      - '9644:9644'
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  mysql_monolith_data:
  mysql_product_data:
  mysql_inventory_data:
  mysql_sales_data:
  redpanda_data:
