services:
  mysql-monolith:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: archkit_monolith
      MYSQL_USER: archkit_user
      MYSQL_PASSWORD: archkit_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_monolith_data:/var/lib/mysql

volumes:
  mysql_monolith_data:
